GENDERED = "gendered"
MASC = "masc"
FEM = "fem"
PLUR = "plur"
PLURS = "plurs"
UNI = "uni"
WOM = 'w'
MAN = 'm'
GENDERS = {WOM, MAN}
STAR_WARS = "Star Wars"
OGL = "OGL"
SW_TAG = "sw"
OGL_TAG = "fantasy"
GAMES = {STAR_WARS: SW_TAG, OGL: OGL_TAG}
